pipeline {
    agent any    
    
	    parameters {
       
         string(defaultValue: "", description: 'Credencias da AWS', name: 'AWS_ACCESS_KEY_ID')
		 string(defaultValue: "", description: 'Credencias da AWS', name: 'AWS_SECRET_ACCESS_KEY')
    }
	
    stages {		
		
		stage('Gerar token') { 
			steps {							
				sh "chmod +x jenkins/gerar_token.sh"
				sh "./jenkins/gerar_token.sh"							
			}			
		}
		
        stage('Deploy') { 
            steps {
                echo "Realizando Deploy S3 e EB" 							
			sh "docker run --rm -e AWS_ACCESS_KEY_ID='${params.AWS_ACCESS_KEY_ID}' -e AWS_SECRET_ACCESS_KEY='${params.AWS_SECRET_ACCESS_KEY}' -e VERSAO='${env.BUILD_ID}' -e OPCAO='Deploy' renatoadsumus/aws_cli:latest"
				          
            }
        }		
        
    }
	
	post {
		always {
		cleanWs()
		}
	}
 }