pipeline {
    agent any    
    
    stages {		
		
        stage('Deploy') { 
            steps {
                echo "Realizando Deploy S3 e EB" 							
			sh "docker run -d --rm -e AWS_ACCESS_KEY_ID='${params.AWS_ACCESS_KEY_ID}' -e AWS_SECRET_ACCESS_KEY='${params.AWS_SECRET_ACCESS_KEY}' -e VERSAO='${env.BUILD_ID}' -e OPCAO='Deploy' renatoadsumus/aws_cli:latest"
				          
            }
        }		
        
    }
 }