pipeline {
    agent any 
    parameters {
       
         string(defaultValue: "", description: 'Credencias da AWS', name: 'AWS_ACCESS_KEY_ID')
		 string(defaultValue: "", description: 'Credencias da AWS', name: 'AWS_SECRET_ACCESS_KEY')
    }
    
    stages {      		

		stage('Gerar token') { 
			steps {							
				sh "chmod +x jenkins/gerar_token.sh"
				sh "./jenkins/gerar_token.sh"							
			}			
		}
		
		
		stage('Run') { 
			steps {			
				echo "Executando Container Docker AWS CLI"				
				//sh "docker run -d --rm -e AWS_ACCESS_KEY_ID='${params.AWS_ACCESS_KEY_ID}' -e AWS_SECRET_ACCESS_KEY='${params.AWS_SECRET_ACCESS_KEY}' -e VERSAO='${env.BUILD_ID}' -e OPCAO='Novo' renatoadsumus/aws_cli:latest"
						
			}			
		}	
        
    }
 }